# Generated by Django 4.1 on 2022-09-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='foto'),
        ),
    ]
