# Generated by Django 4.1 on 2022-09-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_alter_platos_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platos',
            name='foto',
        ),
    ]
